name: Build and Deploy
on:
  push:
    # Sequence of patterns matched against refs/heads
    # branches:
    #   - master         # Push events on master branch
    # Sequence of patterns matched against refs/tags
    tags:
      - "**"             # Push events to v1 tag
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: ${{ secrets.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.REGISTRY }}
          tag_names: true
      - name: Save docker image name
        shell: bash
        run: |
          echo ${{ secrets.REGISTRY_INTERNAL }}/${{ secrets.IMAGE_NAME }}:${{ steps.publish.outputs.tag }} > name.txt
      - name: Upload docker image name for deploy
        uses: actions/upload-artifact@v1
        with:
          name: image
          path: name.txt
